### ISSUE TITLE
Log app errors to db (?) and display them to admin panel

### ISSUE THREAD

**Issue by GeoDoo** [GeoDoo/post-your-standup#130]
Ideally, we would like to have a Reporting tab or sth similar that logs all errors and meaningful info about them, so we can potentially solve them.

**Comment by elefher** [comment]
We can use a service like https://www.bugsnag.com/ or https://docs.sentry.io/product/ instead. It's simple and quick. They offer monitoring systems, admin panel, emails, notifications etc.

**Comment by GeoDoo** [comment]
App wide errors is here: 

https://slack.dev/bolt-js/concepts#error-handling

**Comment by GeoDoo** [comment]
Ok, in the end, after some trial and error with bugsnag, we decided to move with a custom logger!!
